default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mortuary_development

test:
  <<: *default
  database: mortuary_test

production:
  <<: *default
  database: mortuary_production
  username: mortuary
  password: <%= ENV['MORTUARY_DATABASE_PASSWORD'] %>
